export const ADD_PERSONALITYINFORMATION = "ADD_PERSONALITYINFORMATION"
export const ADD_CASTMOVIE = "ADD_CASTMOVIE"
export const ADD_CREWMOVIE = "ADD_CREWMOVIE"
export const ADD_APPOINTMENTS = "ADD_APPOINTMENTS"
